In [2]:
import numpy as np

In [4]:
import pandas as pd

In [6]:
df=pd.read_csv("/content/Restaurant_3.csv")

In [8]:
df.tail()

,DATE,TIME,INVOICE_NO,ITEM,QUANTITY,RATE,SUB_TOTAL,AMOUNT,DAY,CATEGORY,PERSON
608,02-10-2023,22.12,9159,GOLI SODA,3,30,90,728.0,2_,BEVRAGE,NaN
609,02-10-2023,22.12,9159,GHEE PODI ROAST,1,60,60,NaN,2_,MAIN DISH,NaN
610,02-10-2023,22.12,9159,CHICKEN PALLIPALAYAM,1,120,120,NaN,2_,GRAVY,NaN
611,02-10-2023,22.12,9159,PEPPER CHICKEN MASALA,1,130,130,NaN,2_,GRAVY,NaN
612,02-10-2023,22.12,9159,MUSHROOM CHILLI,1,80,80,NaN,2_,STARTER,NaN

In [11]:
df.head()

,DATE,TIME,INVOICE_NO,ITEM,QUANTITY,RATE,SUB_TOTAL,AMOUNT,DAY,CATEGORY,PERSON
0,01-10-2023,12.08,3,CHAPPATHI,3,18,54,54.0,1_,MAIN DISH,1.0
1,01-10-2023,12.15,4,CHILLI CHICKEN,1,100,100,320.0,1_,STARTER,2.0
2,01-10-2023,12.15,4,CHICKEN BIRIYANI,2,110,220,NaN,1_,MAIN DISH,NaN
3,01-10-2023,12.15,5,PAROTTA,2,18,36,36.0,1_,MAIN DISH,1.0
4,01-10-2023,12.36,7,KALAKI,1,15,15,69.0,1_,STARTER,1.0

In [13]:
df.shape

(613, 11)

In [17]:
df.describe()

,TIME,INVOICE_NO,QUANTITY,RATE,SUB_TOTAL,AMOUNT,PERSON
count,613.000000,613.000000,613.000000,613.000000,613.000000,243.000000,243.000000
mean,18.219250,686.773246,1.750408,57.918434,77.970636,196.691358,1.901235
std,3.414651,2126.360182,2.189850,46.909974,66.920662,150.282652,1.316817
min,12.080000,1.000000,1.000000,10.000000,10.000000,35.000000,1.000000
25%,15.010000,55.000000,1.000000,18.000000,36.000000,89.500000,1.000000
50%,19.420000,102.000000,1.000000,35.000000,70.000000,151.000000,2.000000
75%,21.270000,154.000000,2.000000,100.000000,100.000000,268.000000,2.000000
max,23.400000,9159.000000,44.000000,530.000000,792.000000,792.000000,15.000000

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 613 entries, 0 to 612
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   DATE        613 non-null    object
 1   TIME        613 non-null    float64
 2   INVOICE_NO  613 non-null    int64
 3   ITEM        613 non-null    object
 4   QUANTITY    613 non-null    int64
 5   RATE        613 non-null    int64
 6   SUB_TOTAL   613 non-null    int64
 7   AMOUNT      243 non-null    float64
 8   DAY         613 non-null    object
 9   CATEGORY    606 non-null    object
 10  PERSON      243 non-null    float64
dtypes: float64(3), int64(4), object(4)
memory usage: 52.8+ KB

In [20]:
df.isnull()

,DATE,TIME,INVOICE_NO,ITEM,QUANTITY,RATE,SUB_TOTAL,AMOUNT,DAY,CATEGORY,PERSON
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,True,False,False,True
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
608,False,False,False,False,False,False,False,False,False,False,True
609,False,False,False,False,False,False,False,True,False,False,True
610,False,False,False,False,False,False,False,True,False,False,True
611,False,False,False,False,False,False,False,True,False,False,True
612,False,False,False,False,False,False,False,True,False,False,True