In [1]:
import numpy as np

In [3]:
import pandas as pd

In [5]:
df=pd.read_csv("/content/iron_alloys.csv")

In [7]:
df.shape

(1392, 110)

In [9]:
df.describe()

,"Elastic (Young's, Tensile) Modulus (psi)",Elongation at Break (%),Shear Modulus (psi),Tensile Strength: Ultimate (UTS) (psi),Tensile Strength: Yield (Proof) (psi),Compressive (Crushing) Strength (psi),Fracture Toughness (MPa·m^0.5),Shear Strength (psi),Impact Strength: V-Notched Charpy (lb),Fatigue Strength (psi),...,Tantalum (Ta)Ta min,Tantalum (Ta)Ta max,Cerium (Ce)Ce min,Cerium (Ce)Ce max,Lanthanum (La)La min,Lanthanum (La)La max,Zinc (Zn)Zn min,Zinc (Zn)Zn max,Lead (Pb)Pb min,Lead (Pb)Pb max
count,1392.000000,1176.000000,1391.000000,1389.000000,1124.000000,31.000000,20.000000,823.000000,335.000000,976.000000,...,5.000000,5.00000,10.000000,10.000000,3.000000,3.000000,1.000,1.0,3.000000,3.000000
mean,192.830460,21.824660,74.700935,651.187905,401.880783,1038.709677,43.600000,427.120292,57.217313,277.951844,...,0.210000,0.66000,0.030500,0.084000,0.010000,0.080000,0.001,0.1,0.050000,0.120000
std,6.711043,11.494569,3.008332,250.899448,231.268314,499.791569,37.954821,143.356001,27.748978,119.913528,...,0.328634,0.60663,0.013834,0.011738,0.013229,0.017321,NaN,NaN,0.086603,0.199186
min,140.000000,1.000000,54.000000,140.000000,84.000000,570.000000,10.000000,180.000000,7.600000,69.000000,...,0.000000,0.10000,0.000000,0.070000,0.000000,0.070000,0.001,0.1,0.000000,0.005000
25%,190.000000,12.000000,73.000000,510.000000,250.000000,730.000000,17.250000,340.000000,34.000000,200.000000,...,0.000000,0.10000,0.030000,0.080000,0.002500,0.070000,0.001,0.1,0.000000,0.005000
50%,190.000000,20.000000,73.000000,620.000000,340.000000,750.000000,27.500000,410.000000,49.000000,250.000000,...,0.000000,0.50000,0.030000,0.080000,0.005000,0.070000,0.001,0.1,0.000000,0.005000
75%,200.000000,28.000000,77.000000,730.000000,480.000000,1275.000000,58.500000,475.000000,90.000000,330.000000,...,0.300000,1.30000,0.030000,0.095000,0.015000,0.085000,0.001,0.1,0.075000,0.177500
max,210.000000,60.000000,82.000000,2450.000000,2300.000000,2400.000000,160.000000,1470.000000,130.000000,1280.000000,...,0.750000,1.30000,0.050000,0.100000,0.025000,0.100000,0.001,0.1,0.150000,0.350000

In [11]:
df.head()

,iron_alloy_name,"Elastic (Young's, Tensile) Modulus (psi)",Elongation at Break (%),Shear Modulus (psi),Tensile Strength: Ultimate (UTS) (psi),Tensile Strength: Yield (Proof) (psi),Compressive (Crushing) Strength (psi),Fracture Toughness (MPa·m^0.5),Shear Strength (psi),Impact Strength: V-Notched Charpy (lb),...,Tantalum (Ta)Ta min,Tantalum (Ta)Ta max,Cerium (Ce)Ce min,Cerium (Ce)Ce max,Lanthanum (La)La min,Lanthanum (La)La max,Zinc (Zn)Zn min,Zinc (Zn)Zn max,Lead (Pb)Pb min,Lead (Pb)Pb max
0,SAE-ASTM Grade G2500 (F10005) Grey Cast Iron,180,14.0,69.0,190.0,120.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,SAE-ASTM Grade G2500a (F10009) Grey Cast Iron,180,14.0,69.0,190.0,120.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,SAE-ASTM Grade G3000 (F10006) Grey Cast Iron,180,9.6,70.0,220.0,150.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,SAE-ASTM Grade G4000d (F10012) Grey Cast Iron,180,9.6,70.0,290.0,180.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ASTM A897 Grade 1 (ASTM 130-90-09 or 900-650-0...,180,10.0,69.0,1010.0,740.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df.isnull().sum()

iron_alloy_name                                0
Elastic (Young's, Tensile) Modulus (psi)       0
Elongation at Break (%)                      216
Shear Modulus (psi)                            1
Tensile Strength: Ultimate (UTS) (psi)         3
                                            ...
Lanthanum (La)La max                        1389
Zinc (Zn)Zn min                             1391
Zinc (Zn)Zn max                             1391
Lead (Pb)Pb min                             1389
Lead (Pb)Pb max                             1389
Length: 110, dtype: int64