In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("/content/steel fatigue strength prediction.csv")

In [4]:
df.describe()

,Sl. No.,NT,THT,THt,THQCr,CT,Ct,DT,Dt,QmT,...,S,Ni,Cr,Cu,Mo,RedRatio,dA,dB,dC,Fatigue
count,437.000000,437.000000,437.000000,437.000000,437.000000,437.000000,437.000000,437.000000,437.000000,437.000000,...,437.000000,437.000000,437.000000,437.000000,437.000000,437.000000,437.000000,437.000000,437.000000,437.000000
mean,219.000000,872.299771,737.643021,25.949657,10.654462,128.855835,40.502059,123.699844,4.843936,35.491991,...,0.014611,0.517048,0.570458,0.067780,0.069794,923.629291,0.047181,0.003391,0.007712,552.903890
std,126.295289,26.212073,280.036541,10.263824,7.841437,281.743539,126.924697,267.128933,15.700076,19.419277,...,0.006145,0.852976,0.411769,0.049161,0.088124,576.617020,0.031093,0.008240,0.010418,186.630528
min,1.000000,825.000000,30.000000,0.000000,0.000000,30.000000,0.000000,30.000000,0.000000,30.000000,...,0.003000,0.010000,0.010000,0.010000,0.000000,240.000000,0.000000,0.000000,0.000000,225.000000
25%,110.000000,865.000000,845.000000,30.000000,8.000000,30.000000,0.000000,30.000000,0.000000,30.000000,...,0.010000,0.020000,0.120000,0.020000,0.000000,590.000000,0.020000,0.000000,0.000000,448.000000
50%,219.000000,870.000000,845.000000,30.000000,8.000000,30.000000,0.000000,30.000000,0.000000,30.000000,...,0.015000,0.060000,0.710000,0.060000,0.000000,740.000000,0.040000,0.000000,0.000000,505.000000
75%,328.000000,870.000000,855.000000,30.000000,8.000000,30.000000,0.000000,30.000000,0.000000,30.000000,...,0.019000,0.460000,0.980000,0.100000,0.170000,1228.000000,0.070000,0.000000,0.010000,578.000000
max,437.000000,930.000000,865.000000,30.000000,24.000000,930.000000,540.000000,903.333000,70.200000,140.000000,...,0.030000,2.780000,1.170000,0.260000,0.240000,5530.000000,0.130000,0.050000,0.058000,1190.000000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 437 entries, 0 to 436
Data columns (total 27 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Sl. No.   437 non-null    int64
 1   NT        437 non-null    int64
 2   THT       437 non-null    int64
 3   THt       437 non-null    int64
 4   THQCr     437 non-null    int64
 5   CT        437 non-null    int64
 6   Ct        437 non-null    float64
 7   DT        437 non-null    float64
 8   Dt        437 non-null    float64
 9   QmT       437 non-null    int64
 10  TT        437 non-null    int64
 11  Tt        437 non-null    int64
 12  TCr       437 non-null    float64
 13  C         437 non-null    float64
 14  Si        437 non-null    float64
 15  Mn        437 non-null    float64
 16  P         437 non-null    float64
 17  S         437 non-null    float64
 18  Ni        437 non-null    float64
 19  Cr        437 non-null    float64
 20  Cu        437 non-null    float64
 21  Mo        437 non-null    float64
 22  RedRatio  437 non-null    int64
 23  dA        437 non-null    float64
 24  dB        437 non-null    float64
 25  dC        437 non-null    float64
 26  Fatigue   437 non-null    int64
dtypes: float64(16), int64(11)
memory usage: 92.3 KB

In [6]:
df.shape

(437, 27)

In [7]:
df.Fatigue

0       232
1       235
2       235
3       241
4       225
       ...
432    1030
433     957
434    1104
435    1008
436     882
Name: Fatigue, Length: 437, dtype: int64

In [8]:
df.head()

,Sl. No.,NT,THT,THt,THQCr,CT,Ct,DT,Dt,QmT,...,S,Ni,Cr,Cu,Mo,RedRatio,dA,dB,dC,Fatigue
0,1,885,30,0,0,30,0.0,30.0,0.0,30,...,0.022,0.01,0.02,0.01,0.0,825,0.07,0.02,0.04,232
1,2,885,30,0,0,30,0.0,30.0,0.0,30,...,0.017,0.08,0.12,0.08,0.0,610,0.11,0.00,0.04,235
2,3,885,30,0,0,30,0.0,30.0,0.0,30,...,0.015,0.02,0.03,0.01,0.0,1270,0.07,0.02,0.00,235
3,4,885,30,0,0,30,0.0,30.0,0.0,30,...,0.024,0.01,0.02,0.01,0.0,1740,0.06,0.00,0.00,241
4,5,885,30,0,0,30,0.0,30.0,0.0,30,...,0.022,0.01,0.02,0.02,0.0,825,0.04,0.02,0.00,225

Warning: Total number of columns (27) exceeds max_columns (20) limiting to first (20) columns.

In [9]:
df.tail()

,Sl. No.,NT,THT,THt,THQCr,CT,Ct,DT,Dt,QmT,...,S,Ni,Cr,Cu,Mo,RedRatio,dA,dB,dC,Fatigue
432,433,930,30,0,0,930,340.2,895.812,70.2,140,...,0.024,0.02,0.91,0.01,0.15,240,0.050,0.010,0.000,1030
433,434,930,30,0,0,930,340.2,895.812,70.2,140,...,0.015,0.07,1.08,0.08,0.15,530,0.017,0.004,0.008,957
434,435,930,30,0,0,930,340.2,895.812,70.2,60,...,0.019,0.06,1.17,0.07,0.17,690,0.080,0.000,0.000,1104
435,436,930,30,0,0,930,340.2,895.812,70.2,60,...,0.024,0.02,0.91,0.01,0.15,240,0.050,0.010,0.000,1008
436,437,930,30,0,0,930,340.2,895.812,70.2,60,...,0.015,0.07,1.08,0.08,0.15,530,0.017,0.004,0.008,882

In [10]:
df.isnull().sum()

Sl. No.     0
NT          0
THT         0
THt         0
THQCr       0
CT          0
Ct          0
DT          0
Dt          0
QmT         0
TT          0
Tt          0
TCr         0
C           0
Si          0
Mn          0
P           0
S           0
Ni          0
Cr          0
Cu          0
Mo          0
RedRatio    0
dA          0
dB          0
dC          0
Fatigue     0
dtype: int64